### ISSUE TITLE
Wifi connection attempt, failure, and messaing

### ISSUE THREAD

**Issue by digableinc** [theapplicationist/cryptotracker_nodemcu#1]
Added wifi connection process with messaging for the user. init.lua will now attempt to connect to wifi, keep track of attempts and fail with messaging.

If it succeeds, it messages the user with the IP address, and will then start getting coin information. This will prevent HTTP/DNS errors if the WiFi never connects. Also gives the user overall insight into what the program is doing/attempting.

[init.lua.zip](https://github.com/theapplicationist/cryptotracker_nodemcu/files/1791276/init.lua.zip)

**Comment by theapplicationist** [comment]
I added your improvements to the init file. Thanks, Very useful!
